import SEO from "@/components/SEO";
import { APP_TITLE } from "@/const";
import Header from "@/components/Header";
import { PawPrint } from "lucide-react";

export default function Terms() {
  const currentDate = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  return (
    <div className="min-h-screen flex flex-col">
      <SEO
        title={`Terms of Service & Disclaimer | ${APP_TITLE}`}
        description="Terms of Service and Disclaimer for PetCost-Calculator.com. Please read these terms carefully before using our calculator."
        canonical="https://www.petcost-calculator.com/terms"
        breadcrumbs={[
          { name: "Home", url: "https://www.petcost-calculator.com" },
          { name: "Terms of Service", url: "https://www.petcost-calculator.com/terms" }
        ]}
      />
      <Header />
      
      <div className="flex-grow bg-background">
        <div className="container mx-auto px-4 py-12 max-w-4xl">
          <h1 className="text-4xl font-bold mb-4 pb-4 border-b-2 border-border">
            Terms of Service & Disclaimer
          </h1>
          <p className="text-muted-foreground mb-8">
            <strong>Last updated:</strong> {currentDate}
          </p>

          <section className="mb-12 bg-muted/30 p-6 rounded-lg border border-border">
            <h2 className="text-2xl font-semibold mb-4 text-primary">
              Important Disclaimer
            </h2>
            <p className="text-foreground/90 leading-relaxed mb-4">
              The content and tools provided on <strong>PetCost-Calculator.com</strong> are for informational and educational purposes only. The cost estimates generated by our calculator are indicative averages based on publicly available data, user surveys, and industry research. 
            </p>
            <p className="text-foreground/90 leading-relaxed mb-4">
              <strong>These estimates do not constitute financial, veterinary, or professional advice.</strong> Actual costs of pet ownership will vary significantly based on your specific location, your pet's individual health needs, inflation, and your personal choices regarding care and services.
            </p>
            <p className="text-foreground/90 leading-relaxed">
              Always consult with qualified veterinary professionals and financial advisors before making decisions about pet adoption or ownership. We strongly recommend maintaining an emergency fund or securing pet insurance, as unexpected medical costs can far exceed our estimates.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-4 text-primary">
              1. Acceptance of Terms
            </h2>
            <p className="text-foreground/90 leading-relaxed">
              By accessing and using PetCost-Calculator.com ("the Website"), you accept and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our Website or calculator tools.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-4 text-primary">
              2. Use of the Calculator
            </h2>
            <p className="text-foreground/90 leading-relaxed mb-4">
              Our calculator is provided as a free tool to help prospective pet owners budget. You agree to use this tool responsibly and not to:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-foreground/90">
              <li>Attempt to reverse engineer, scrape, or extract data from the calculator via automated means.</li>
              <li>Use the estimates as a guarantee of actual future costs.</li>
              <li>Hold PetCost-Calculator.com liable for any financial decisions made based on our estimates.</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-4 text-primary">
              3. Advertising and Revenue Disclosure
            </h2>
            <p className="text-foreground/90 leading-relaxed">
              To keep this tool 100% free for all users, PetCost-Calculator.com is supported by advertising revenue, primarily through Google AdSense. We may display advertisements throughout the site. We do not endorse the products or services advertised, and we are not responsible for the content of third-party advertisements or the websites they link to.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-4 text-primary">
              4. Intellectual Property
            </h2>
            <p className="text-foreground/90 leading-relaxed">
              All content, design, algorithms, and data structures on this Website are the intellectual property of PetCost-Calculator.com. You may download and share the PDF reports generated by the calculator for personal, non-commercial use. You may not republish, reproduce, or distribute our proprietary data or articles without explicit written permission.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-4 text-primary">
              5. Limitation of Liability
            </h2>
            <p className="text-foreground/90 leading-relaxed">
              To the maximum extent permitted by law, PetCost-Calculator.com and its creators shall not be liable for any direct, indirect, incidental, consequential, or special damages arising out of or in any way connected with your use of our Website or reliance on our cost estimates. The tool is provided "as is" without warranties of any kind, either express or implied.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-4 text-primary">
              6. Changes to Terms
            </h2>
            <p className="text-foreground/90 leading-relaxed">
              We reserve the right to modify these Terms of Service at any time. We will notify users of any changes by updating the "Last updated" date at the top of this page. Your continued use of the Website after any modifications indicates your acceptance of the updated terms.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold mb-4 text-primary">
              7. Contact Information
            </h2>
            <p className="text-foreground/90 leading-relaxed">
              If you have any questions about these Terms of Service, please contact us at:
              <br /><br />
              📧 <strong><a href="mailto:hello@petcost-calculator.com" className="text-primary hover:underline">hello@petcost-calculator.com</a></strong>
            </p>
          </section>
        </div>
      </div>

      {/* Footer */}
      <footer className="border-t py-8 mt-auto bg-white">
        <div className="container">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-2">
              <PawPrint className="h-6 w-6 text-primary" />
              <span className="text-sm font-semibold">PetCost-Calculator.com</span>
            </div>
            <div className="flex gap-6 text-sm text-muted-foreground">
              <a href="/about" className="hover:text-primary transition-colors">About</a>
              <a href="/how-it-works" className="hover:text-primary transition-colors">How It Works</a>
              <a href="/contact" className="hover:text-primary transition-colors">Contact</a>
              <a href="/privacy-policy" className="hover:text-primary transition-colors">Privacy Policy</a>
              <a href="/terms" className="hover:text-primary transition-colors">Terms of Service</a>
            </div>
            <p className="text-sm text-muted-foreground">
              © {new Date().getFullYear()} PetCost-Calculator.com. All rights reserved.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}
