// All images sourced from Wikimedia Commons (public domain / CC licensed)
// Using Special:FilePath redirect — no hash needed, resolves to current file location
// CSS rule: all breed image containers use object-cover object-top for face-centred display

const WM = (filename: string) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(filename)}?width=600`;

export const dogBreedImageMap: Record<string, string> = {
  "affenpinscher":                   WM("Affenpinscher.jpg"),
  "afghan-hound":                    WM("Afghan_Hound_in_Tallinn.jpg"),
  "airedale-terrier":                WM("Airedale_Terrier_600.jpg"),
  "akita":                           WM("Akita_Inu_dog.jpg"),
  "alaskan-malamute":                WM("Alaskan_Malamute.jpg"),
  "american-eskimo-dog":             WM("American_Eskimo_Dog.jpg"),
  "american-staffordshire-terrier":  WM("American_Staffordshire_Terrier_-_Amber.jpg"),
  "australian-cattle-dog":           WM("Australian_Cattle_Dog_photo.jpg"),
  "australian-shepherd":             WM("Australian_Shepherd_red_tri.jpg"),
  "australian-terrier":              WM("Australian_Terrier.jpg"),
  "basenji":                         WM("Basenji_profile_photo.jpg"),
  "basset-hound":                    WM("Basset_hound_profile.jpg"),
  "beagle":                          WM("Beagle_600.jpg"),
  "bearded-collie":                  WM("Bearded_Collie_600.jpg"),
  "belgian-malinois":                WM("Belgian_Malinois.jpg"),
  "bernese-mountain-dog":            WM("BerneseMountainDog_wb.jpg"),
  "bichon-frise":                    WM("Bichon_Frise_600.jpg"),
  "bloodhound":                      WM("Bloodhound_2308867537.jpg"),
  "border-collie":                   WM("Border_Collie_600.jpg"),
  "border-terrier":                  WM("Border_Terrier_600.jpg"),
  "boston-terrier":                  WM("Boston_Terrier_Buddy.jpg"),
  "boxer":                           WM("Boxer_lying_yawning.jpg"),
  "briard":                          WM("Briard.jpg"),
  "brittany":                        WM("Brittany_Spaniel_600.jpg"),
  "bull-terrier":                    WM("Bull_Terrier_photo.jpg"),
  "bulldog":                         WM("Bulldog_inglese.jpg"),
  "bullmastiff":                     WM("Bullmastiff.jpg"),
  "cairn-terrier":                   WM("Cairn-terrier.jpg"),
  "cane-corso":                      WM("Cane_corso_ferruccio.jpg"),
  "cardigan-welsh-corgi":            WM("Cardigan.Welsh.Corgi.Merle.jpg"),
  "cavalier-king-charles-spaniel":   WM("KingCharlesSpaniels.jpg"),
  "chesapeake-bay-retriever":        WM("Chesapeake_Bay_Retriever.jpg"),
  "chihuahua":                       WM("Chihuahua1_bvdb.jpg"),
  "chow-chow":                       WM("Chow-Chow.jpg"),
  "clumber-spaniel":                 WM("Clumber_Spaniel_600.jpg"),
  "cocker-spaniel":                  WM("Cocker_Spaniel_600.jpg"),
  "collie":                          WM("Rough_Collie_EOS_7D_20130510_7758.jpg"),
  "dachshund":                       WM("Dachshund_black_and_tan.jpg"),
  "dalmatian":                       WM("Dalmatian_dog_photo.jpg"),
  "doberman-pinscher":               WM("Dobermann_handling.jpg"),
  "english-cocker-spaniel":          WM("English_Cocker_Spaniel_600.jpg"),
  "english-setter":                  WM("English_Setter_600.jpg"),
  "english-springer-spaniel":        WM("English_Springer_Spaniel_Photo.jpg"),
  "field-spaniel":                   WM("Field_Spaniel_600.jpg"),
  "french-bulldog":                  WM("French_Bulldog_001.jpg"),
  "german-shepherd":                 WM("German_Shepherd_Dog_bi_color_Titus.jpg"),
  "german-shorthaired-pointer":      WM("German_Shorthaired_Pointer.jpg"),
  "giant-schnauzer":                 WM("Giant_Schnauzer_600.jpg"),
  "golden-retriever":                WM("Golden_Retriever_Dukedestiny01_drvd.jpg"),
  "gordon-setter":                   WM("Gordon_Setter_600.jpg"),
  "great-dane":                      WM("Great_Dane_001.jpg"),
  "great-pyrenees":                  WM("Pyrenees_mountain_dog.jpg"),
  "greyhound":                       WM("Greyhound_Racing_dog.jpg"),
  "havanese":                        WM("Havanese_dog.jpg"),
  "irish-setter":                    WM("Irish_Setter_600.jpg"),
  "irish-terrier":                   WM("Irish_Terrier_600.jpg"),
  "irish-wolfhound":                 WM("Irish_Wolfhound_600.jpg"),
  "italian-greyhound":               WM("Italian_Greyhound.jpg"),
  "jack-russell-terrier":            WM("Jack_Russell_Terrier_600.jpg"),
  "keeshond":                        WM("Keeshond_600.jpg"),
  "kerry-blue-terrier":              WM("Kerry_Blue_Terrier.jpg"),
  "komondor":                        WM("Komondor_dog.jpg"),
  "labrador-retriever":              WM("Labrador_Retriever_portrait.jpg"),
  "lhasa-apso":                      WM("Lhasa_Apso.jpg"),
  "maltese":                         WM("Maltese_600.jpg"),
  "mastiff":                         WM("English_Mastiff.jpg"),
  "miniature-pinscher":              WM("Miniature_Pinscher_600.jpg"),
  "miniature-schnauzer":             WM("Miniature_Schnauzer.jpg"),
  "newfoundland":                    WM("Newfoundland_dog_running.jpg"),
  "norwegian-elkhound":              WM("Norwegian_Elkhound.jpg"),
  "old-english-sheepdog":            WM("Old_English_Sheepdog_Photo.jpg"),
  "papillon":                        WM("Papillon_Dog.jpg"),
  "pekingese":                       WM("Pekingese_EM1B0428.jpg"),
  "pembroke-welsh-corgi":            WM("CorgiRest.jpg"),
  "pomeranian":                      WM("Pomeranian_new.jpg"),
  "poodle":                          WM("Standard_poodle_brown.jpg"),
  "portuguese-water-dog":            WM("Portuguese_Water_Dog.jpg"),
  "pug":                             WM("Mops_IMG_1033.jpg"),
  "rhodesian-ridgeback":             WM("Rhodesian_Ridgeback_photo.jpg"),
  "rottweiler":                      WM("Rottweiler_standing_facing_left.jpg"),
  "saint-bernard":                   WM("Saint_Bernard_dog.jpg"),
  "saluki":                          WM("Saluki_dog.jpg"),
  "samoyed":                         WM("Samoyed_dog_Polar.jpg"),
  "schipperke":                      WM("Schipperke.jpg"),
  "scottish-terrier":                WM("Scottish_Terrier_600.jpg"),
  "shetland-sheepdog":               WM("Shetland_Sheepdog_photo.jpg"),
  "shiba-inu":                       WM("Shiba_inu_taiki.jpg"),
  "shih-tzu":                        WM("Shihtzu.jpg"),
  "siberian-husky":                  WM("Black-Magic-Big-Boy.jpg"),
  "soft-coated-wheaten-terrier":     WM("Soft_Coated_Wheaten_Terrier_600.jpg"),
  "staffordshire-bull-terrier":      WM("Staffordshire_Bull_Terrier_photo.jpg"),
  "tibetan-mastiff":                 WM("Tibetan_Mastiff_600.jpg"),
  "toy-poodle":                      WM("Toy_poodle_apricot.jpg"),
  "vizsla":                          WM("Vizsla_dog.jpg"),
  "weimaraner":                      WM("Weimaraner.jpg"),
  "welsh-corgi":                     WM("CorgiRest.jpg"),
  "west-highland-white-terrier":     WM("West_Highland_White_Terrier.jpg"),
  "whippet":                         WM("Whippet_600.jpg"),
  "wire-fox-terrier":                WM("Wire_Fox_Terrier_600.jpg"),
  "yorkshire-terrier":               WM("Yorkshireterrier.jpg"),
};

export const catBreedImageMap: Record<string, string> = {
  "abyssinian":         WM("Gustav_chocolate.jpg"),
  "american-bobtail":  WM("American_Bobtail.jpg"),
  "american-curl":     WM("American_curl_2.jpg"),
  "american-shorthair":WM("CreamAmericanShorthair.jpg"),
  "balinese":          WM("Balinese_cat_-_Siam_Bali.jpg"),
  "bengal":            WM("Paintedcats_Red_Star_standing.jpg"),
  "birman":            WM("Birmankatze.jpg"),
  "bombay":            WM("Bombay_cat_2.jpg"),
  "british-shorthair": WM("Britishblue.jpg"),
  "burmese":           WM("Sable_Burmese_female.jpg"),
  "chartreux":         WM("Chartreux_cat.jpg"),
  "cornish-rex":       WM("CornishRex.jpg"),
  "devon-rex":         WM("Devon_Rex.jpg"),
  "egyptian-mau":      WM("Egyptian_Mau_Bronze_MC.jpg"),
  "exotic-shorthair":  WM("Exotic_Shorthair_cat.jpg"),
  "himalayan":         WM("Himalayan_cat_-_Wikipedia.jpg"),
  "japanese-bobtail":  WM("Japanese_Bobtail_Red_White.jpg"),
  "maine-coon":        WM("Maine_Coon_cat_by_Tomitheos.JPG"),
  "manx":              WM("Manx_cat_2.jpg"),
  "munchkin":          WM("Munchkin_Katze.jpg"),
  "norwegian-forest-cat": WM("Andrew_-_Norwegian_Forest_Cat.jpg"),
  "ocicat":            WM("Ocicat_-_Calypso_of_Ambala.jpg"),
  "persian":           WM("White_Persian_Cat.jpg"),
  "ragdoll":           WM("Ragdoll_cat.jpg"),
  "russian-blue":      WM("RussianBlue.jpg"),
  "savannah":          WM("Savannah_Cat_2006.jpg"),
  "scottish-fold":     WM("Scottish_fold_cat_on_olive_tree.jpg"),
  "siamese":           WM("Siamese_cat_(traditional_style).jpg"),
  "siberian":          WM("Siberian_cat_from_Yaroslavl.jpg"),
  "singapura":         WM("Singapura_Cats.jpg"),
  "somali":            WM("Somali_cat.jpg"),
  "sphynx":            WM("Sphynx1_July_2006.jpg"),
  "tonkinese":         WM("Tonkinese_cat.jpg"),
  "turkish-angora":    WM("Turkish_angora_2.jpg"),
  "turkish-van":       WM("Turkish_Van_Cat.jpg"),
};

const DEFAULT_DOG_IMG = WM("Golden_Retriever_Dukedestiny01_drvd.jpg");
const DEFAULT_CAT_IMG = WM("White_Persian_Cat.jpg");

export function getBreedImage(breedId: string, petType: "dog" | "cat"): string {
  if (petType === "dog") {
    return dogBreedImageMap[breedId] ?? DEFAULT_DOG_IMG;
  }
  return catBreedImageMap[breedId] ?? DEFAULT_CAT_IMG;
}
